from .hr import (  # noqa: F401
    AttendanceRecord,
    Department,
    Designation,
    Employee,
    LeaveRequest,
    PayrollRecord,
    PayrollSettings,
    Permission,
    Role,
    SalaryStructureOverride,
    Shift,
    ShiftAssignment,
    User,
)